/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/localize_legacy_message_ids/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-localize-legacy-message-ids-should-add-legacy-message-ids-if-enablei18nlegacymessageidformat-is-true-legacy-enabled',
    category: 'i18n',
    description:
      'Angular compliance: should add legacy message ids if `enableI18nLegacyMessageIdFormat` is true',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n-title title=\"Some &amp; attribute\"></div>\n  <div i18n>Some &amp; message</div>\n  <div i18n-title title=\"Some &amp; {{'interpolated'}} attribute\"></div>\n  <div i18n>Some &amp; {{'interpolated' }} message</div>\n  <div i18n>&amp;</div>\n  <div i18n>&amp;&quot;</div>\n  <div i18n-title title=\"&quot;\"></div>\n  <div i18n-title title=\"&quot;&quot;\"></div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-localize-legacy-message-ids-should-not-add-legacy-message-ids-if-enablei18nlegacymessageidformat-is-false-legacy-disabled',
    category: 'i18n',
    description:
      'Angular compliance: should not add legacy message ids if `enableI18nLegacyMessageIdFormat` is false',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>Some Message</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
]
