/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.1.5:
 * r3_view_compiler_i18n/element_attributes/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-element-attributes-should-add-the-meaning-and-description-as-jsdoc-comments-and-metadata-blocks-meaning-description',
    category: 'i18n',
    description:
      'Angular compliance: should add the meaning and description as JsDoc comments and metadata blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div i18n="meaningA|descA@@idA">Content A</div>\n  <div i18n-title="meaningB|descB@@idB" title="Title B">Content B</div>\n  <div i18n-title="meaningC|" title="Title C">Content C</div>\n  <div i18n-title="meaningD|descD" title="Title D">Content D</div>\n  <div i18n-title="meaningE@@idE" title="Title E">Content E</div>\n  <div i18n-title="@@idF" title="Title F">Content F</div>\n  <div i18n-title="[BACKUP_$\\{MESSAGE}_ID:idH]\\`desc@@idG" title="Title G">Content G</div>\n  <div i18n="Some text \\\\\' [BACKUP_MESSAGE_ID: xxx]">Content H</div>\n`,\n    standalone: false\n})\nexport class MyComponent {\n}\n\n',
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-i18n-attributes-on-explicit-ng-template-elements-ng-template-basic',
    category: 'i18n',
    description:
      'Angular compliance: should support i18n attributes on explicit <ng-template> elements',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template i18n-title title=\"Hello\"></ng-template>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-i18n-attributes-on-explicit-ng-template-with-structural-directives-ng-template-structural',
    category: 'i18n',
    description:
      'Angular compliance: should support i18n attributes on explicit <ng-template> with structural directives',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template *ngIf=\"visible\" i18n-title title=\"Hello\">Test</ng-template>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  visible = false;\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-i18n-attributes-with-interpolations-on-explicit-ng-template-elements-ng-template-interpolation',
    category: 'i18n',
    description:
      'Angular compliance: should support i18n attributes with interpolations on explicit <ng-template> elements',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template i18n-title title=\"Hello {{ name }}\"></ng-template>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  name = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-i18n-attributes-with-interpolations-on-explicit-ng-template-elements-with-structural-directives-ng-t',
    category: 'i18n',
    description:
      'Angular compliance: should support i18n attributes with interpolations on explicit <ng-template> elements with structural directives',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template *ngIf=\"true\" i18n-title title=\"Hello {{ name }}\"></ng-template>\n`,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  name = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-not-create-translations-for-empty-attributes-empty-attributes',
    category: 'i18n',
    description: 'Angular compliance: should not create translations for empty attributes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div id=\"static\" i18n-title=\"m|d\" title></div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-not-create-translations-for-bound-attributes-bound-attributes',
    category: 'i18n',
    description: 'Angular compliance: should not create translations for bound attributes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div\n  [title]=\"title\" i18n-title\n  [attr.label]=\"label\" i18n-attr.label>\n  </div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  title = '';\n  label = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-translate-static-attributes-static-attributes',
    category: 'i18n',
    description: 'Angular compliance: should translate static attributes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div id="static" i18n-title="m|d" title="introduction"></div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n',
  },
  {
    name: 'i18n-compliance-element-attributes-should-translate-static-attributes-when-used-on-an-element-with-structural-directive-static-attributes-structural',
    category: 'i18n',
    description:
      'Angular compliance: should translate static attributes when used on an element with structural directive',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n    <div *ngIf="exp" id="static" i18n-title="m|d" title="introduction"></div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  exp = true;\n}\n\n',
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-interpolation-interpolation-basic',
    category: 'i18n',
    description: 'Angular compliance: should support interpolation',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component, Directive, Input, Pipe} from \'@angular/core\';\n\n@Pipe({\n    name: \'uppercase\',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Directive({\n    selector: \'div\',\n    standalone: true\n})\nexport class DivDir {\n  @Input(\'aria-label\') al!: any;\n  @Input(\'aria-roledescription\') arl!: any;\n}\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div id="dynamic-1"\n    i18n-title="m|d" title="intro {{ valueA | uppercase }}"\n    i18n-aria-label="m1|d1" aria-label="{{ valueB }}"\n    i18n-aria-roledescription aria-roledescription="static text"\n  ></div>\n  <div id="dynamic-2"\n    i18n-title="m2|d2" title="{{ valueA }} and {{ valueB }} and again {{ valueA + valueB }}"\n    i18n-aria-roledescription aria-roledescription="{{ valueC }}"\n  ></div>\n  `,\n    standalone: true, imports: [CommonModule, UppercasePipe, DivDir]\n})\nexport class MyComponent {\n  valueA: any;\n  valueB: any;\n  valueC: any;\n}\n\n',
  },
  {
    name: 'i18n-compliance-element-attributes-should-correctly-bind-to-context-in-nested-template-interpolation-nested-context',
    category: 'i18n',
    description: 'Angular compliance: should correctly bind to context in nested template',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div *ngFor=\"let outer of items\">\n    <div i18n-title=\"m|d\" title=\"different scope {{ outer | uppercase }}\"></div>\n  </div>\n  `,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  outer = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-complex-expressions-in-interpolation-interpolation-complex-expressions',
    category: 'i18n',
    description: 'Angular compliance: should support complex expressions in interpolation',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n-title title=\"{{valueA.getRawValue()?.getTitle()}} title\"></div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  valueA!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-support-complex-expressions-in-interpolation-with-legacyoptionalchaining-interpolation-complex-expressions-u',
    category: 'i18n',
    description:
      'Angular compliance: should support complex expressions in interpolation with legacyOptionalChaining',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n-title title=\"{{valueA.getRawValue()?.getTitle()}} title\"></div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  valueA!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-work-correctly-when-placed-on-i18n-root-node-i18n-root-node',
    category: 'i18n',
    description: 'Angular compliance: should work correctly when placed on i18n root node',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n i18n-title=\"m|d\" title=\"Element title\">Some content</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-element-attributes-should-sanitize-ids-and-generate-proper-variable-names-invalid-i18n-meta',
    category: 'i18n',
    description: 'Angular compliance: should sanitize ids and generate proper variable names',
    className: 'MyComponent',
    type: 'full-transform',
    i18nUseExternalIds: false,
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div i18n="@@ID.WITH.INVALID.CHARS.2" i18n-title="@@ID.WITH.INVALID.CHARS" title="Element title">\n    Some content\n  </div>\n  `,\n    standalone: false\n})\nexport class MyComponent {\n}\n\n',
  },
]
