/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/self-closing_i18n_instructions/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-self-closing-i18n-instructions-should-be-generated-with-text-only-content-text-only-content',
    category: 'i18n',
    description: 'Angular compliance: should be generated with text-only content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>My i18n block #1</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-self-closing-i18n-instructions-should-be-generated-for-icu-only-i18n-blocks-icu-only',
    category: 'i18n',
    description: 'Angular compliance: should be generated for ICU-only i18n blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{age, select, 10 {ten} 20 {twenty} other {other}}</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  age = 1;\n}\n\n",
  },
  {
    name: 'i18n-compliance-self-closing-i18n-instructions-should-be-generated-within-ng-container-and-ng-template-blocks-ng-container-ng-template',
    category: 'i18n',
    description:
      'Angular compliance: should be generated within <ng-container> and <ng-template> blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template i18n>My i18n block #1</ng-template>\n  <ng-container i18n>My i18n block #2</ng-container>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-self-closing-i18n-instructions-should-not-be-generated-in-case-we-have-styling-instructions-styles',
    category: 'i18n',
    description: 'Angular compliance: should not be generated in case we have styling instructions',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <span i18n class=\"myClass\">Text #1</span>\n  <span i18n style=\"padding: 10px;\">Text #2</span>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
]
