/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/whitespace_preserving_mode/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-whitespace-preserving-mode-should-keep-inner-content-of-i18n-block-as-is-preserve-inner-content',
    category: 'i18n',
    description: 'Angular compliance: should keep inner content of i18n block as is',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    Some text\n    <span>Text inside span</span>\n  </div>\n`,\n    preserveWhitespaces: true,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
]
