/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.1.5:
 * r3_view_compiler_i18n/icu_logic/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-icu-logic-should-handle-single-icus-single-icu',
    category: 'i18n',
    description: 'Angular compliance: should handle single icus',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>before {gender, select, male {male} female {female} other {other}} after</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'male';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-properly-escape-quotes-in-content-escape-quotes',
    category: 'i18n',
    description: 'Angular compliance: should properly escape quotes in content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{gender, select, single {'single quotes'} double {\"double quotes\"} other {other}}</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'male';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-support-icu-only-templates-icu-only',
    category: 'i18n',
    description: 'Angular compliance: should support ICU-only templates',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  {age, select, 10 {ten} 20 {twenty} other {other}}\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  age = 20;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-generate-i18n-instructions-for-icus-generated-outside-of-i18n-blocks-bare-icu',
    category: 'i18n',
    description:
      'Angular compliance: should generate i18n instructions for icus generated outside of i18n blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div>{gender, select, male {male} female {female} other {other}}</div>\n  <div *ngIf="visible" title="icu only">\n    {age, select, 10 {ten} 20 {twenty} other {other}}\n  </div>\n  <div *ngIf="available" title="icu and text">\n    You have {count, select, 0 {no emails} 1 {one email} other {{{count}} emails}}.\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = \'female\';\n}\n\n',
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-icus-with-html-html-content',
    category: 'i18n',
    description: 'Angular compliance: should handle icus with html',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {gender, select, male {male - <b>male</b>} female {female <b>female</b>} other {<div class=\"other\"><i>other</i></div>}}\n    <b>Other content</b>\n    <div class=\"other\"><i>Another content</i></div>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'female';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-icus-with-expressions-expressions',
    category: 'i18n',
    description: 'Angular compliance: should handle icus with expressions',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{gender, select, male {male of age: {{ ageA + ageB + ageC }}} female {female} other {other}}</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'female';\n  ageA = 1;\n  ageB = 2;\n  ageC = 3;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-multiple-icus-in-one-block-multiple-icus',
    category: 'i18n',
    description: 'Angular compliance: should handle multiple icus in one block',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {gender, select, male {male} female {female} other {other}}\n    {age, select, 10 {ten} 20 {twenty} 30 {thirty} other {other}}\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'male';\n  age = 1;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-multiple-icus-that-share-same-placeholder-shared-placeholder',
    category: 'i18n',
    description: 'Angular compliance: should handle multiple icus that share same placeholder',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {gender, select, male {male} female {female} other {other}}\n    <div>\n      {gender, select, male {male} female {female} other {other}}\n    </div>\n    <div *ngIf=\"visible\">\n      {gender, select, male {male} female {female} other {other}}\n    </div>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'male';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-nested-icus-nested-icus',
    category: 'i18n',
    description: 'Angular compliance: should handle nested icus',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {gender, select,\n      male {male of age: {age, select, 10 {ten} 20 {twenty} 30 {thirty} other {other}}}\n      female {female}\n      other {other}\n    }\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  age = 1;\n  gender = 'male';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-nested-with-interpolations-in-other-blocks-nested-icu-in-other-block',
    category: 'i18n',
    description: 'Angular compliance: nested with interpolations in "other" blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{count, plural,\n    =0 {zero}\n    =2 {{{count}} {name, select,\n          cat {cats}\n          dog {dogs}\n          other {animals}} !}\n    other {other - {{count}}}\n  }</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  count = 0;\n  name = 'Andrew';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-icus-in-different-contexts-different-contexts',
    category: 'i18n',
    description: 'Angular compliance: should handle icus in different contexts',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n  {gender, select, male {male} female {female} other {other}}\n  <span *ngIf=\"ageVisible\">\n    {age, select, 10 {ten} 20 {twenty} 30 {thirty} other {other}}\n  </span>\n</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'female';\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-icus-with-interpolations-icu-with-interpolations',
    category: 'i18n',
    description: 'Angular compliance: should handle icus with interpolations',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {gender, select, male {male {{ weight }}} female {female {{ height }}} other {other}}\n    <span *ngIf=\"ageVisible\">\n      {age, select, 10 {ten} 20 {twenty} 30 {thirty} other {other: {{ otherAge }}}}\n    </span>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'male';\n  weight = 1;\n  height = 1;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-icus-with-named-interpolations-named-interpolations',
    category: 'i18n',
    description: 'Angular compliance: should handle icus with named interpolations',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{\n    gender,\n    select,\n      male {male {{ weight // i18n(ph=\"PH_A\") }}}\n      female {female {{ height // i18n(ph=\"PH_B\") }}}\n      other {other {{ age // i18n(ph=\"PH WITH SPACES\") }}}\n  }</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'male';\n  weight = 1;\n  height = 1;\n  age = 1;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-attach-metadata-in-case-an-icu-represents-the-whole-message-metadata',
    category: 'i18n',
    description:
      'Angular compliance: should attach metadata in case an ICU represents the whole message',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n=\"meaningA|descA@@idA\">{count, select, 1 {one} other {more than one}}</div>\n`,\n    standalone: false\n})\nexport class MyComponent {\n  count = 1;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-produce-proper-messages-when-select-or-plural-keywords-have-spaces-after-them-keyword-spaces',
    category: 'i18n',
    description:
      'Angular compliance: should produce proper messages when `select` or `plural` keywords have spaces after them',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {count, select , 1 {one} other {more than one}}\n    {count, plural , =1 {one} other {more than one}}\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  count = 0;\n}\n\n",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handle-icus-with-element-tags-as-the-root-message-root-icu-with-elements',
    category: 'i18n',
    description: 'Angular compliance: should handle ICUs with element tags, as the root message',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n  selector: 'my-component',\n  template: `\n    <span i18n=\"someText1\">{\n      someField,\n      select,\n      WEBSITE {\n        <strong>someText</strong>\n      }\n    }</span>\n\n    <span>\n    {\n      someField,\n      select,\n      WEBSITE {\n        <strong>someText</strong>\n      }\n    }\n    </span>\n`,\n})\nexport class MyComponent {\n  someField!: any;\n}",
  },
  {
    name: 'i18n-compliance-icu-logic-should-handles-icus-with-html-content-that-has-interpolated-attributes-attribute-interpolation',
    category: 'i18n',
    description:
      'Angular compliance: should handles ICUs with html content that has interpolated attributes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n  selector: 'my-comp',\n  template: `\n  <div i18n>\n    <span title=\"{{foo}}-{{foo}}\"></span>\n    <span>{foo, select, other {<span title=\"{{foo}}-{{foo}}\">foo</span>}}</span>\n    <span>{foo, select, other {{{foo}}-{{foo}}}}</span>\n  </div>\n  `\n})\nexport class MyComponent {\n  foo: any;\n}\n",
  },
]
