/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.1.5:
 * r3_view_compiler_i18n/blocks/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-blocks-should-support-if-blocks-conditional',
    category: 'i18n',
    description: 'Angular compliance: should support @if blocks',
    className: 'MyApp',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    template: `\n    <div i18n>\n      Content:\n      @if (count === 0) {\n        before<span>zero</span>after\n      } @else if (count === 1) {\n        before<div>one</div>after\n      } @else {\n        before<button>otherwise</button>after\n      }!\n\n      @if (count === 7) {\n        before<span>seven</span>after\n      }\n    </div>\n  `,\n    standalone: false\n})\nexport class MyApp {\n  count = 0;\n}\n",
  },
  {
    name: 'i18n-compliance-blocks-should-support-switch-blocks-switch',
    category: 'i18n',
    description: 'Angular compliance: should support @switch blocks',
    className: 'MyApp',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    template: `\n    <div i18n>\n      Content:\n      @switch (count) {\n        @case (0) {before<span>zero</span>after}\n        @case (1) {before<div>one</div>after}\n        @default {before<button>otherwise</button>after}\n      }\n    </div>\n  `,\n    standalone: false\n})\nexport class MyApp {\n  count = 0;\n}\n",
  },
  {
    name: 'i18n-compliance-blocks-should-support-for-blocks-for',
    category: 'i18n',
    description: 'Angular compliance: should support @for blocks',
    className: 'MyApp',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    template: `\n    <div i18n>\n      Content:\n      @for (item of items; track item) {\n        before<span>middle</span>after\n      } @empty {\n        before<div>empty</div>after\n      }!\n    </div>\n  `,\n    standalone: false\n})\nexport class MyApp {\n  items = [1, 2, 3];\n}\n",
  },
  {
    name: 'i18n-compliance-blocks-should-support-defer-blocks-defer',
    category: 'i18n',
    description: 'Angular compliance: should support @defer blocks',
    className: 'MyApp',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    template: `\n    <div i18n>\n      Content:\n      @defer (when isLoaded) {\n        before<span>middle</span>after\n      } @placeholder {\n        before<div>placeholder</div>after\n      } @loading {\n        before<button>loading</button>after\n      } @error {\n        before<h1>error</h1>after\n      }\n    </div>\n  `,\n    standalone: false\n})\nexport class MyApp {\n  isLoaded = false;\n}\n",
  },
]
