/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/namespaces/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-namespaces-should-handle-namespaces-inside-i18n-blocks-foreign-object',
    category: 'i18n',
    description: 'Angular compliance: should handle namespaces inside i18n blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <svg xmlns=\"http://www.w3.org/2000/svg\">\n    <foreignObject i18n>\n      <xhtml:div xmlns=\"http://www.w3.org/1999/xhtml\">\n        Count: <span>5</span>\n      </xhtml:div>\n    </foreignObject>\n  </svg>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-namespaces-should-handle-namespaces-on-i18n-block-containers-namespaced-div',
    category: 'i18n',
    description: 'Angular compliance: should handle namespaces on i18n block containers',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <svg xmlns=\"http://www.w3.org/2000/svg\">\n    <foreignObject>\n      <xhtml:div xmlns=\"http://www.w3.org/1999/xhtml\" i18n>\n        Count: <span>5</span>\n      </xhtml:div>\n    </foreignObject>\n  </svg>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
]
