/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.1.5:
 * r3_view_compiler_i18n/ng-container_ng-template/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-single-translation-message-using-ng-container-single-ng-container',
    category: 'i18n',
    description:
      'Angular compliance: should handle single translation message using <ng-container>',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-container i18n>Some content: {{ valueA | uppercase }}</ng-container>\n`,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  valueA = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-single-translation-message-using-ng-template-single-ng-template',
    category: 'i18n',
    description: 'Angular compliance: should handle single translation message using <ng-template>',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template i18n>Some content: {{ valueA | uppercase }}</ng-template>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-be-able-to-act-as-child-elements-inside-i18n-block-child-elements',
    category: 'i18n',
    description: 'Angular compliance: should be able to act as child elements inside i18n block',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    <ng-template>Template content: {{ valueA | uppercase }}</ng-template>\n    <ng-container>Container content: {{ valueB | uppercase }}</ng-container>\n  </div>\n`,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  valueA = '';\n  valueB = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-icus-outside-of-translatable-sections-bare-icus',
    category: 'i18n',
    description: 'Angular compliance: should handle ICUs outside of translatable sections',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template>{gender, select, male {male} female {female} other {other}}</ng-template>\n  <ng-container>{age, select, 10 {ten} 20 {twenty} other {other}}</ng-container>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  age = 0;\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-correctly-propagate-i18n-context-through-nested-templates-nested-templates',
    category: 'i18n',
    description:
      'Angular compliance: should correctly propagate i18n context through nested templates',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    <ng-template>\n      Template A: {{ valueA | uppercase }}\n      <ng-template>\n        Template B: {{ valueB }}\n        <ng-template>\n          Template C: {{ valueC }}\n        </ng-template>\n      </ng-template>\n    </ng-template>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-work-with-icus-icus',
    category: 'i18n',
    description: 'Angular compliance: should work with ICUs',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-container i18n>{gender, select, male {male} female {female} other {other}}</ng-container>\n  <ng-template i18n>{age, select, 10 {ten} 20 {twenty} other {other}}</ng-template>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  gender = 'female';\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-self-closing-tags-as-content-self-closing-tags',
    category: 'i18n',
    description: 'Angular compliance: should handle self-closing tags as content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <ng-container i18n>\n    <img src="logo.png" title="Logo" /> is my logo #1\n  </ng-container>\n  <ng-template i18n>\n    <img src="logo.png" title="Logo" /> is my logo #2\n  </ng-template>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n',
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-not-emit-duplicate-i18n-consts-for-elements-with-the-same-content-duplicate-content',
    category: 'i18n',
    description:
      'Angular compliance: should not emit duplicate i18n consts for elements with the same content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>Test</div>\n  <div i18n>Test</div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-generate-a-self-closing-container-instruction-for-ng-container-inside-i18n-self-closing-ng-container',
    category: 'i18n',
    description:
      'Angular compliance: should generate a self-closing container instruction for ng-container inside i18n',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    Hello <ng-container>there</ng-container>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-not-generate-a-self-closing-container-instruction-for-ng-container-with-non-text-ng-container-with-non',
    category: 'i18n',
    description:
      'Angular compliance: should not generate a self-closing container instruction for ng-container with non-text ',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    Hello <ng-container>there <strong>!</strong></ng-container>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-structural-directives-structural-directives',
    category: 'i18n',
    description: 'Angular compliance: should handle structural directives',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <ng-template *ngIf=\"someFlag\" i18n>Content A</ng-template>\n  <ng-container *ngIf=\"someFlag\" i18n>Content B</ng-container>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-structural-directives-with-same-placeholder-structural-directives-same-placeholder',
    category: 'i18n',
    description: 'Angular compliance: should handle structural directives with same placeholder',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div i18n>\n    <div *ngIf="someFlag">Content</div>\n    <div *ngIf="someFlag">\n      <div *ngIf="someFlag">Content</div>\n    </div>\n\n    <img *ngIf="someOtherFlag" />\n    <img *ngIf="someOtherFlag" />\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n',
  },
  {
    name: 'i18n-compliance-ng-container-ng-template-should-handle-templates-in-sibling-i18n-blocks-sibling-i18n-blocks',
    category: 'i18n',
    description: 'Angular compliance: should handle templates in sibling i18n blocks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n  selector: 'my-component',\n  template: `\n  <div i18n>\n    <ng-template>Content A</ng-template>\n  </div>\n  <div i18n>\n    <ng-template>Content B</ng-template>\n  </div>\n`,\n})\nexport class MyComponent {\n}\n",
  },
]
