/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-root-should-allow-repeating-the-same-placeholder-repeated-placeholder',
    category: 'i18n',
    description: 'Angular compliance: should allow repeating the same placeholder',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n    <div i18n>Hello, {{ placeholder }}! You are a very good {{ placeholder }}.</div>\n    <div i18n>Hello, {{ placeholder // i18n(ph = \"ph\") }}! Hello again {{ placeholder // i18n(ph = \"ph\") }}.</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  placeholder: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-root-should-support-i18n-message-with-multiple-pipes-multiple-pipes',
    category: 'i18n',
    description: 'Angular compliance: should support i18n message with multiple pipes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe, PipeTransform} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{{ valueA | pipeA }} and {{ valueB | pipeB }}</div>\n  <div i18n><span>{{ valueA | pipeA }}</span> and {{ valueB | pipeB }} <span>and {{ valueC | pipeC }}</span></div>\n`,\n    standalone: true, imports: [CommonModule, PipeA, PipeB, PipeC]\n})\nexport class MyComponent {\n  valueA = 0;\n  valueB = 0;\n  valueC = 0;\n}\n\n@Pipe({\n    name: 'pipeA',\n    standalone: true\n})\nexport class PipeA implements PipeTransform {\n  transform() {\n    return null;\n  }\n}\n\n@Pipe({\n    name: 'pipeB',\n    standalone: true\n})\nexport class PipeB implements PipeTransform {\n  transform() {\n    return null;\n  }\n}\n\n@Pipe({\n    name: 'pipeC',\n    standalone: true\n})\nexport class PipeC implements PipeTransform {\n  transform() {\n    return null;\n  }\n}\n\n",
  },
  {
    name: 'i18n-compliance-root-should-support-i18n-nodes-with-icus-inside-icu-and-i18n',
    category: 'i18n',
    description: 'Angular compliance: should support i18n nodes with ICUs inside',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n  selector: 'my-component',\n  template: `\n    <div i18n>\n      <div *ngFor=\"let diskView of disks\">\n        {{diskView.name}} has {diskView.length, plural, =1 {VM} other {VMs}}\n      </div>\n    </div>\n  `,\n})\nexport class MyComponent {\n  disks: any;\n}\n",
  },
]
