/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/line_ending_normalization/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-line-ending-normalization-should-normalize-line-breaks-for-non-legacy-messages-in-inline-templates-where-i18nnormalizelineendingsinicu',
    category: 'i18n',
    description:
      "Angular compliance: should normalize line breaks for non-legacy messages in 'inline templates' where i18nNormalizeLineEndingsInICUs is true",
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: This template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    template: `\n<div title=\"abc\r\ndef\" i18n-title i18n>\r\nSome Message\r\n{\r\n  value,\r\n  select,\r\n  =0 {\r\n    zero\r\n  }\r\n}</div>`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-normalize-line-breaks-for-non-legacy-messages-in-inline-templates-where-i18nnormalizelineendingsinicu',
    category: 'i18n',
    description:
      "Angular compliance: should normalize line breaks for non-legacy messages in 'inline templates' where i18nNormalizeLineEndingsInICUs is false",
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: This template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    template: `\n<div title=\"abc\r\ndef\" i18n-title i18n>\r\nSome Message\r\n{\r\n  value,\r\n  select,\r\n  =0 {\r\n    zero\r\n  }\r\n}</div>`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-normalize-line-breaks-for-non-legacy-messages-in-external-templates-where-i18nnormalizelineendingsini',
    category: 'i18n',
    description:
      "Angular compliance: should normalize line breaks for non-legacy messages in 'external templates' where i18nNormalizeLineEndingsInICUs is true",
    className: 'MyComponent',
    type: 'full-transform',
    skipReason: 'external templates are not supported by the compare tool',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: The template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    templateUrl: 'template.html',\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-normalize-line-breaks-for-non-legacy-messages-in-external-templates-where-i18nnormalizelineendingsini',
    category: 'i18n',
    description:
      "Angular compliance: should normalize line breaks for non-legacy messages in 'external templates' where i18nNormalizeLineEndingsInICUs is false",
    className: 'MyComponent',
    type: 'full-transform',
    skipReason: 'external templates are not supported by the compare tool',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: The template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    templateUrl: 'template.html',\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-compute-normalized-legacy-ids-for-messages-in-inline-templates-where-i18nnormalizelineendingsinicus-i',
    category: 'i18n',
    description:
      'Angular compliance: should compute normalized legacy ids for messages in inline templates where i18nNormalizeLineEndingsInICUs is true',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: This template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    template: `\n<div title=\"abc\r\ndef\" i18n-title i18n>\r\nSome Message\r\n{\r\n  value,\r\n  select,\r\n  =0 {\r\n    zero\r\n  }\r\n}</div>`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-compute-normalized-legacy-ids-for-messages-in-inline-templates-where-i18nnormalizelineendingsinicus-i',
    category: 'i18n',
    description:
      'Angular compliance: should compute normalized legacy ids for messages in inline templates where i18nNormalizeLineEndingsInICUs is false',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: This template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    template: `\n<div title=\"abc\r\ndef\" i18n-title i18n>\r\nSome Message\r\n{\r\n  value,\r\n  select,\r\n  =0 {\r\n    zero\r\n  }\r\n}</div>`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-compute-normalized-legacy-ids-for-messages-in-external-templates-where-i18nnormalizelineendingsinicus',
    category: 'i18n',
    description:
      'Angular compliance: should compute normalized legacy ids for messages in external templates where i18nNormalizeLineEndingsInICUs is true',
    className: 'MyComponent',
    type: 'full-transform',
    skipReason: 'external templates are not supported by the compare tool',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: The template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    templateUrl: 'template.html',\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-line-ending-normalization-should-compute-non-normalized-legacy-ids-for-messages-in-external-templates-where-i18nnormalizelineendingsin',
    category: 'i18n',
    description:
      'Angular compliance: should compute non-normalized legacy ids for messages in external templates where i18nNormalizeLineEndingsInICUs is false',
    className: 'MyComponent',
    type: 'full-transform',
    skipReason: 'external templates are not supported by the compare tool',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    // NOTE: The template has escaped `\\r\\n` line-endings markers that will be converted to real\n    // `\\r\\n` line-ending chars when loaded from the test file-system.\n    templateUrl: 'template.html',\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  value!: any;\n}\n\n",
  },
]
