/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.0.0:
 * r3_view_compiler_i18n/nested_nodes/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-nested-nodes-should-not-produce-instructions-for-empty-content-empty-content',
    category: 'i18n',
    description: 'Angular compliance: should not produce instructions for empty content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n></div>\n  <div i18n>  </div>\n  <div i18n>\n\n  </div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-ignore-html-comments-within-translated-text-comments-in-translated-text',
    category: 'i18n',
    description: 'Angular compliance: should ignore HTML comments within translated text',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>Some <!-- comments --> text</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-properly-escape-quotes-in-content-escape-quotes',
    category: 'i18n',
    description: 'Angular compliance: should properly escape quotes in content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>Some text 'with single quotes', \"with double quotes\", \\`with backticks\\` and without quotes.</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-interpolations-wrapped-in-backticks-backtick-quotes',
    category: 'i18n',
    description: 'Angular compliance: should handle interpolations wrapped in backticks',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: '<div i18n>`{{ count }}`</div>',\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  count = 1;\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-attributes-with-plain-text-content-plain-text-messages',
    category: 'i18n',
    description: 'Angular compliance: should handle i18n attributes with plain-text content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>My i18n block #1</div>\n  <div>My non-i18n block #1</div>\n  <div i18n>My i18n block #2</div>\n  <div>My non-i18n block #2</div>\n  <div i18n>My i18n block #3</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-support-named-interpolations-named-interpolations',
    category: 'i18n',
    description: 'Angular compliance: should support named interpolations',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    Named interpolation: {{ valueA // i18n(ph=\"PH_A\") }}\n    Named interpolation with spaces: {{ valueB // i18n(ph=\"PH B\") }}\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  valueA = '';\n  valueB = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-support-interpolations-with-complex-expressions-interpolation-complex-expressions',
    category: 'i18n',
    description: 'Angular compliance: should support interpolations with complex expressions',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'async',\n    standalone: true\n})\nexport class AsyncPipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    {{ valueA | async }}\n    {{ valueA?.a?.b }}\n    {{ valueA.getRawValue()?.getTitle() }}\n  </div>\n  `,\n    standalone: true, imports: [CommonModule, AsyncPipe]\n})\nexport class MyComponent {\n  valueA!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-attributes-with-bindings-in-content-bindings-in-content',
    category: 'i18n',
    description: 'Angular compliance: should handle i18n attributes with bindings in content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>My i18n block #{{ one }}</div>\n  <div i18n>My i18n block #{{ two | uppercase }}</div>\n  <div i18n>My i18n block #{{ three + four + five }}</div>\n  `,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  one = 1;\n  two = 2;\n  three = 3;\n  four = 4;\n  five = 5;\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-attributes-with-bindings-and-nested-elements-in-content-nested-elements',
    category: 'i18n',
    description:
      'Angular compliance: should handle i18n attributes with bindings and nested elements in content',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n    My i18n block #{{ one }}\n    <span>Plain text in nested element</span>\n  </div>\n  <div i18n>\n    My i18n block #{{ two | uppercase }}\n    <div>\n      <div>\n        <span>\n          More bindings in more nested element: {{ nestedInBlockTwo }}\n        </span>\n      </div>\n    </div>\n  </div>\n`,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  one = 1;\n  two = 2;\n  nestedInBlockTwo = '';\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-attributes-with-bindings-in-content-and-element-attributes-nested-elements-with-i18n-attributes',
    category: 'i18n',
    description:
      'Angular compliance: should handle i18n attributes with bindings in content and element attributes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Pipe} from '@angular/core';\n\n@Pipe({\n    name: 'uppercase',\n    standalone: true\n})\nexport class UppercasePipe {\n  transform(v: any) {}\n}\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>\n  My i18n block #1 with value: {{ valueA }}\n  <span i18n-title title=\"Span title {{ valueB }} and {{ valueC }}\">\n    Plain text in nested element (block #1)\n  </span>\n</div>\n<div i18n>\n  My i18n block #2 with value {{ valueD | uppercase }}\n  <span i18n-title title=\"Span title {{ valueE }}\">\n    Plain text in nested element (block #2)\n  </span>\n</div>\n`,\n    standalone: true, imports: [CommonModule, UppercasePipe]\n})\nexport class MyComponent {\n  valueA!: any;\n  valueB!: any;\n  valueC!: any;\n  valueD!: any;\n  valueE!: any;\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-attributes-in-nested-templates-nested-templates',
    category: 'i18n',
    description: 'Angular compliance: should handle i18n attributes in nested templates',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div>\n    Some content\n    <div *ngIf=\"visible\">\n      <div i18n>\n        Some other content {{ valueA }}\n        <div>\n          More nested levels with bindings {{ valueB | uppercase }}\n        </div>\n      </div>\n    </div>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-ignore-i18n-attributes-on-self-closing-tags-self-closing',
    category: 'i18n',
    description: 'Angular compliance: should ignore i18n attributes on self-closing tags',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <img src="logo.png" i18n />\n  <img src="logo.png" i18n *ngIf="visible" />\n  <img src="logo.png" i18n *ngIf="visible" i18n-title title="App logo #{{ id }}" />\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n',
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-context-in-nested-templates-nested-templates-context',
    category: 'i18n',
    description: 'Angular compliance: should handle i18n context in nested templates',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      'import {CommonModule} from \'@angular/common\';\nimport {Component} from \'@angular/core\';\n\n@Component({\n    selector: \'my-component\',\n    template: `\n  <div i18n>\n    Some content\n    <div *ngIf="visible">\n      Some other content {{ valueA }}\n      <div>\n        More nested levels with bindings {{ valueB | uppercase }}\n        <div *ngIf="exists">\n          Content inside sub-template {{ valueC }}\n          <div>\n            Bottom level element {{ valueD }}\n          </div>\n        </div>\n      </div>\n    </div>\n    <div *ngIf="!visible">\n      Some other content {{ valueE + valueF }}\n      <div>\n        More nested levels with bindings {{ valueG | uppercase }}\n      </div>\n    </div>\n  </div>\n`,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n',
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-i18n-attribute-with-directives-directives',
    category: 'i18n',
    description: 'Angular compliance: should handle i18n attribute with directives',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n *ngIf=\"visible\">Some other content <span>{{ valueA }}</span></div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-generate-event-listeners-instructions-before-i18n-ones-event-listeners',
    category: 'i18n',
    description:
      'Angular compliance: should generate event listeners instructions before i18n ones',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n (click)=\"onClick()\">Hello</div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  onClick() {}\n}\n\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-ng-content-in-i18n-block-nested-ng-content',
    category: 'i18n',
    description: 'Angular compliance: should handle ng-content in i18n block',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n  selector: 'my-component',\n  template: `\n  <div i18n>\n    <ng-content select=\"special\"></ng-content>\n    <ng-content></ng-content>\n  </div>\n`,\n})\nexport class MyComponent {\n}\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-ng-content-in-i18n-block-i18n-after-binding',
    category: 'i18n',
    description: 'Angular compliance: should handle ng-content in i18n block',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component, Input} from '@angular/core';\n\n@Component({\n  selector: 'my-cmp',\n  template: `\n\t\t<span i18n>\n  \t\t\t<input [disabled]=\"someBoolean\">\n\t\t\t{{ someField }}\n\t\t</span>\n\t`,\n})\nexport class MyComponent {\n  someBoolean = false;\n  someField!: any;\n}\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-should-handle-ng-content-with-i18n-children-ng-content-with-i18n-children',
    category: 'i18n',
    description: 'Angular compliance: should handle ng-content with i18n children',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n  selector: 'my-component',\n  template: `\n    <ng-content>\n      <span i18n=\"@@MY_ID\">a <b>b</b> c</span>\n    </ng-content>\n  `,\n})\nexport class MyComponent {}\n",
  },
  {
    name: 'i18n-compliance-nested-nodes-when-the-last-element-inside-an-i18n-block-has-i18n-attributes-last-elem-inside-i18n-block',
    category: 'i18n',
    description:
      'Angular compliance: when the last element inside an i18n block has i18n attributes',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: `\n  <div i18n>{{ text }}<h1 i18n-title title=\"{{ attr }}\"></h1></div>\n  `,\n    standalone: true, imports: [CommonModule]\n})\nexport class MyComponent {\n  attr: any;\n  text: any;\n}\n\n",
  },
]
