/**
 * Generated by scripts/generate-i18n-fixtures.ts from Angular 22.1.5:
 * r3_view_compiler_i18n/es5_support/TEST_CASES.json
 * Do not edit by hand; re-run the script instead.
 */
import type { Fixture } from '../types.js'

export const fixtures: Fixture[] = [
  {
    name: 'i18n-compliance-es5-support-should-generate-es5-compliant-localized-messages-if-the-target-is-es5-test',
    category: 'i18n',
    description:
      'Angular compliance: should generate ES5 compliant localized messages if the target is ES5',
    className: 'MyComponent',
    type: 'full-transform',
    sourceCode:
      "import {CommonModule} from '@angular/common';\nimport {Component} from '@angular/core';\n\n@Component({\n    selector: 'my-component',\n    template: '<div i18n=\"meaning:A|descA@@idA\">Content A</div>',\n    standalone: false\n})\nexport class MyComponent {\n}\n\n",
  },
]
